In [ ]:
# Page 30: Imports

from math import sqrt # Import only sqrt function from math module
x = 100
# Now, it's imported, we can directly use sqrt to call the math.sqrt()
print(sqrt(x)) # It prints 10

from math import * # Import ALL functions from math module
x = 100
print(sqrt(x)) # It print 10

In [ ]:
# Page 31: Imports

# Import ALL functions from math module, including math.sqrt()
from math import *
# Import ALL functions from cmath module, including cmath.sqrt()
from cmath import *

x = 100
# The following will use cmath.sqrt(), which is a different implementation to
# math.sqrt()
print(sqrt(x)) # It print 10

In [ ]:
# Page 36: Importing Data and Export Data

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/My Drive/training_data.csv', index_col=False)

In [ ]:
# Page 37: Importing Data and Export Data

import pandas as pd
# Create a pandas.DataFrame object with two columns:
# 'CustomerId' and 'CanRepayLoan'
output = pd.DataFrame({'CustomerId': np.array([1, 2, 3]),
                       'CanRepayLoan': np.array([0, 0, 1])})
# Convert the pandas.DataFrame object into the csv "loans .csv" and
# Export it to the root folder of My Drive
output.to_csv('/content/drive/My Drive/loans.csv', index_col=False)

In [ ]:
# Page 39: Arrays

import numpy as np

a = np.array([1, 2, 3])            # Create a rank 1 array
print(type(a))                     # Print "<class 'numpy.ndarray'>"
print(a.shape)                     # Print "(3,)"
print(a[0], a[1], a[2])            # Print "1 2 3"
a[0] = 5                           # Change an element of the array
print(a)                           # Print "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Print "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Print "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
# Page 40: Arrays

import numpy as np

a = np.zeros((2,2))          # Create an array of all zeros
print(a)                     # Print "[[ 0.  0.]
                             #         [ 0.  0.]]"
b = np.ones((1,2))           # Create an array of all ones
print(b)                     # Print "[[ 1.  1.]]"

c = np.full((2,2), 7)        # Create a constant array
print(c)                     # Print "[[ 7.  7.]
                             #         [ 7.  7.]]"
d = np.eye(2)                # Create a 2x2 identity matrix
print(d)                     # Print "[[ 1.  0.]
                             #         [ 0.  1.]]"
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.60718701 0.98232804]
 [0.94894137 0.90994507]]


In [ ]:
# Page 42: Array Indexing

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[1  2  3  4]
#  [5  6  7  8]
#  [9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [ ]:
# Page 43: Array Indexing

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of same rank as the original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
# Page 45: Integer Array Indexing

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
# Page 46: Integer Array Indexing

import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
# Page 47: Boolean Array Indexing

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2; this returns a numpy
                     # array of Booleans of the same shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array consisting of the elements of a
# corresponding to the True values of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
# Page 48: Datatypes

import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [ ]:
# Page 49: Array Math

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
# Page 54: Array Math

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# Page 55: Numpy Functions

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(np.matmul(v, w))
print(v@w)

# Matrix / vector product; both produce the rank 1 array [29 67]
print(np.matmul(x, v))
print(x@v)

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(np.matmul(x, y))
print(x@y)

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# Page 56: Numpy Functions

import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))          # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
# Page 57: Transpose

x = np.array([[1,2], [3,4]])
print(x)               # Print "[[1 2]
                       #         [3 4]]"
print(x.T)             # Print "[[1 3]
                       #         [2 4]]"
print(np.transpose(x)) # Print "[[1 3]
                       #         [2 4]]"
print(x.transpose())   # Print "[[1 3]
                       #         [2 4]]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [ ]:
# Page 59: Transpose

import numpy as np
# Create a 3D array
# (2 layers, 3 rows, and 4 columns)
# with numbers 0 to 23.
arr = np.array([[[ 0,  1,  2,  3],
                 [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]],
                [[12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])

# transpose can re-order the array axes.
# For example, if we want to
# take the current last axis (i.e. 2),
# make it the first axis (put 2 at the front),
# take the current first axis (i.e. 0),
# make it the second axis (put 0 in the middle),
# take the current second axis (i.e. 1),
# and make it the last axis (put 1 at the end).
# We pass transpose [2, 0, 1].
print(np.transpose(arr, [2, 0, 1]))
# Same output if we put the line below
print(arr.transpose([2, 0, 1]))

# Print "[[[ 0  4  8]
#          [12 16 20]
#
#         [[ 1  5  9]
#          [13 17 21]]
#
#         [[ 2  6 10]
#          [14 18 22]]
#
#         [[ 3  7 11]
#          [15 19 23]]]"

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


In [ ]:
# Page 60: Transpose

import numpy as np

v = np.array([1,2,3])
print(v)               # Print "[1 2 3]"
print(v.T)             # Print "[1 2 3]"
print(np.transpose(v)) # Print "[1 2 3]"

[1 2 3]
[1 2 3]
[1 2 3]


In [ ]:
# Page 62: Reshaping

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr1.reshape(4, 3)   # Convert arr1 to a 2D array with 4 rows, 3 columns
# arr2 = arr1.reshape(4,-1) # This line has the same effect as arr1.reshape(4,3)
print(arr2) # Print "[[ 1  2  3]
            #         [ 4  5  6]
            #         [ 7  8  9]
            #         [10 11 12]]"
print("Shape of arr2:", arr2.shape) # Print "Shape of arr2: (4,3)"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of arr2: (4, 3)


In [ ]:
# Page 64: Increasing the Dimensions of an Array using np.newaxis

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # It prints [1 2 3 4 5]

# Convert 1D array to a column matrix
arr2 = arr1[np.newaxis]
print(arr2)  # It prints [[1 2 3 4 5]]

# Convert 1D array to a column matrix
arr3 = arr1[None]
print(arr3)  # It prints [[1 2 3 4 5]]

arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4)  # It prints [[1 2 3]
             #            [4 5 6]]

arr5 = arr4[np.newaxis]
print(arr5)  # It prints [[[1 2 3]
             #             [4 5 6]]]

In [ ]:
# Page 65: Increasing the Dimensions of an Array using np.newaxis

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)  # It prints [[1 2 3]
             #            [4 5 6]]

# np.newaxis means adding a new dimension of size 1, i.e., 1 column
arr2 = arr1[:, :, np.newaxis]  # Equivalent to arr2 = arr1[..., np.newaxis]

print(arr2)  # It prints [[[1]
             #             [2]
             #             [3]]
             #            [[4]
             #             [5]
             #             [6]]]

print(arr2.shape) # It prints (2, 3, 1), which means 2 layers, 3 rows, 1 column

In [ ]:
# Page 66: Increasing the Dimensions of an Array using np.newaxis

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)  # It prints [[1 2 3]
             #            [4 5 6]]

# np.newaxis means adding a new dimension of size 1, i.e., 1 row
# highest dimension, i.e. column
arr2 = arr1[:, np.newaxis, :]

print(arr2)  # It prints [[[1 2 3]]
             #            [[4 5 6]]]

print(arr2.shape) # It prints (2, 1, 3), which means 2 layers, 1 row, 3 columns

In [ ]:
# Page 67: Increasing the Dimensions of an Array using np.expand_dims

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)  # It prints [[1 2 3]
             #            [4 5 6]]

# 2 means adding a new dimension of size 1, after the 2nd dimension
arr2 = np.expand_dims(arr1, 2)

print(arr2)  # It prints [[[1]
             #             [2]
             #             [3]]
             #            [[4]
             #             [5]
             #             [6]]]

print(arr2.shape) # It prints (2, 3, 1), which means 2 layers, 3 rows, 1 column

In [ ]:
# Page 68: Increasing the Dimensions of an Array using np.expand_dims

import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)  # It prints [[1 2 3]
             #            [4 5 6]]

# 1 means adding a new dimension of size 1, after the 1st dimension
arr2 = np.expand_dims(arr1, 1)

print(arr2)  # It prints [[[1 2 3]]
             #            [[4 5 6]]]

print(arr2.shape) # It prints (2, 1, 3), which means 2 layers, 1 row, 3 columns

In [ ]:
# Page 70: Broadcasting - Motivation

import numpy as np

# We will add the vector v to each row of the matrix x, storing the result in y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)  # It prints "[[2 2 4]
          #             [5 5 7]
          #             [8 8 10]
          #             [11 11 13]]"

In [ ]:
# Page 71: Broadcasting - Motivation

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv                # Add x and vv elementwise

print(y)                  # Prints "[[2 2 4]
                          #          [5 5 7]
                          #          [8 8 10]
                          #          [11 11 13]]"


In [ ]:
# Page 72: Broadcasting

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)   # Prints "[[ 2  2  4]
           #          [ 5  5  7]
           #          [ 8  8 10]
           #          [11 11 13]]"

In [ ]:
# Page 74: Understanding Broadcasting Rules

import numpy as np

A = np.array([1, 2, 3])
print(A.ndim)     # Print 1
print(A.shape)    # Print (3,)
B = np.array([2])
print(B.ndim)     # Print 1
print(B.shape)    # Print (1,)
print(A * B)      # Print "[2, 4, 6]"

1
(3,)
1
(1,)
[2 4 6]


In [ ]:
# Page 75: Understanding Broadcasting Rules

import numpy as np

A = np.array([1, 2, 3])
print(A.ndim)  # Print 1
print(A.shape) # Print (3,)
B = np.array([[4, 4, 4], [3, 3, 3]])
print(B.ndim)  # Print 2
print(B.shape) # Print (2,3)
print(A*B)     # Print [[4 8 12]
               #        [3 6 9]]

1
(3,)
2
(2, 3)
[[ 4  8 12]
 [ 3  6  9]]


In [ ]:
# Page 78: Centering an Array

import numpy as np
scores = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
score_mean = scores.mean(0)  # 0 here means the first dimension
print(score_mean)            # Prints array([7., 8., 9.])
scores_centered = scores - score_mean
print(scores_centered)    # Prints array([[-6., -6., -6.],
                          #               [-3., -3., -3.],
                          #               [ 0.,  0.,  0.],
                          #               [ 3.,  3.,  3.],
                          #               [ 6.,  6.,  6.]])
print(score_centered.mean(0))    # Prints array([0., 0., 0.])

In [ ]:
# Page 80, 81, 82: Pairwise Distances

# a shape-(3, 3) array
x = np.array([[ 8.54,  1.54,  8.12],
              [ 3.13,  8.76,  5.29],
              [ 7.73,  6.71,  1.31]])

# a shape-(2, 3) array
y = np.array([[ 8.65,  0.27,  4.67],
              [ 7.73,  7.26,  1.95]])

reshaped_x = x.reshape(3, 1, 3)
reshaped_y = y.reshape(1, 2, 3)
diffs = reshape_x - reshape_y
print("Shape of diffs", diffs.shape)   # Prints (3, 2, 3)

print(diffs)  # It prints [[[-0.11  1.27  3.45]
              #             [ 0.81 -5.72  6.17]]
              #            [[-5.52  8.49  0.62]
              #             [-4.6   1.5   3.34]]
              #            [[-0.92  6.44 -3.36]
              #             [ 0.   -0.55 -0.64]]]

dists = np.sqrt(np.sum(diffs**2, axis=2))  # axis=2 means the layer axis

print(dists)  # It prints [[ 3.67797499  8.45241977]
              #            [10.14568381  5.87925165]
              #            [ 7.32185769  0.84386018]]

print(dists.shape)  # It prints (3, 2), which means 3 rows, 2 columns

In [ ]:
# Page 86: Memory Consumption for Numpy Arrays and Lists

import numpy as np; import sys; import gc  # Import numpy package, system and gc module

def actualsize(input_object):
    memory_size = 0                # memory_size: the actual memory size of "input_object"
                                   # Initialize it to 0
    ids = set()                    # ids: An empty set to store all the ids of objects in "input_object"
    objects = [input_object]       # objects: A list with "input_object" (traverse from "input_object")
    while objects:                 # While "objects" is non-empty
        new = []                   # new: An empty list to keep the items linked by "objects"
        for obj in objects:        # obj: Each object in "objects"
            if id(obj) not in ids: # If the id of "obj" is not in "ids"
               ids.add(id(obj))    # Add the id of the "obj" to "ids"
               memory_size += sys.getsizeof(obj) # Use getsizeof to determine the size of "obj"
                                   # and add it to "memory_size"
               new.append(obj)            # Add "obj" to "new"
        objects = gc.get_referents(*new)  # Update "objects" with the list of objects directly
                                          # referred to by *new
    return memory_size                # Return "memory_size"

L = list(range(0, 1000))           # Define a Python list of 1000 elements
A = np.arange(1000)                # Define a numpy array of 1000 elements
# Print size of the whole list
print("Size of the whole list in bytes:", actualsize(L))        # Print 37116
# Print size of the whole Numpy array
print("Size of the whole numpy array in bytes:", actualsize(A)) # Print 8104

Size of the whole list in bytes: 37116
Size of the whole numpy array in bytes: 8104


In [ ]:
# Page 87: Time Comparison Between Numpy Arrays and Python Lists

import numpy as np       # Import required packages
import time as t

size = 1000000           # Size of arrays and lists

list1 = range(size)      # Declare lists
list2 = range(size)
array1 = np.arange(size) # Declare arrays
array2 = np.arange(size)

# Capture time before the multiplication of Python lists
initialTime = t.time()
# Multiply elements of both the lists and stored in another list
resultList = [(a * b) for a, b in zip(list1, list2)]
# Calculate execution time, it prints "Time taken by Lists: 0.13024258613586426 s"
print("Time taken by Lists:", (t.time() - initialTime), "s")

# Capture time before the multiplication of Numpy arrays
initialTime = t.time()
# Multiply elements of both the Numpy arrays and stored in another Numpy array
resultArray = array1 * array2
# Calculate execution time, it prints "Time taken by NumPy Arrays: 0.006006956100463867 s"
print("Time taken by NumPy Arrays:", (t.time() - initialTime), "s")

Time taken by Lists: 0.13325858116149902 s
Time taken by NumPy Arrays: 0.0038776397705078125 s


In [ ]:
# Page 88: Effect of Operations on Numpy Arrays and Python Lists

import numpy as np # Import Numpy package

ls =[1, 2, 3]      # Declare a list
arr = np.array(ls) # Convert the list into a Numpy array

try:
    ls = ls + 4    # Add 4 to each element of list
except(TypeError):
    print("Lists don't support list + int")

# Now on array
try:
    arr = arr + 4  # Add 4 to each element of Numpy array
    print("Modified Numpy array: ",arr)  # Print the Numpy array
except(TypeError):
    print("Numpy arrays don't support list + int")

Lists don't support list + int
Modified Numpy array:  [5 6 7]
